name: Docker-based Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Builid image
        run: docker build -t ai-summary .

      - name: Run tests with pytest in container
        run: docker run ai-summary "pytest"