name: Docker-based Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Builid image
        run: docker build -f Dockerfile_ci -t ai-summary .

      - name: Testing ...
        run: docker run ai-summary bash -c "pwd && PYTHONPATH=/app pytest"