name: Docker-based Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Builid image
        run: docker build -f Dockerfile_ci -t ai-summary .
      
      - name: Run container
        run: docker run -d -p 8501:8501 --name ai-summary ai-summary

      - name: Testing ...
        run: docker exec -it ai-summary bash -c "cd app && pytest"